In [4]:
import chainladder as cl
import pandas as pd

### Data

In [8]:
triangle = cl.load_sample("genins")
triangle

           12         24         36         48         60         72         84         96         108        120
2001  357848.0  1124788.0  1735330.0  2218270.0  2745596.0  3319994.0  3466336.0  3606286.0  3833515.0  3901463.0
2002  352118.0  1236139.0  2170033.0  3353322.0  3799067.0  4120063.0  4647867.0  4914039.0  5339085.0        NaN
2003  290507.0  1292306.0  2218525.0  3235179.0  3985995.0  4132918.0  4628910.0  4909315.0        NaN        NaN
2004  310608.0  1418858.0  2195047.0  3757447.0  4029929.0  4381982.0  4588268.0        NaN        NaN        NaN
2005  443160.0  1136350.0  2128333.0  2897821.0  3402672.0  3873311.0        NaN        NaN        NaN        NaN
2006  396132.0  1333217.0  2180715.0  2985752.0  3691712.0        NaN        NaN        NaN        NaN        NaN
2007  440832.0  1288463.0  2419861.0  3483130.0        NaN        NaN        NaN        NaN        NaN        NaN
2008  359480.0  1421128.0  2864498.0        NaN        NaN        NaN        NaN        NaN        NaN        NaN
2009  376686.0  1363294.0        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN
2010  344014.0        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN        NaN

In [18]:
latest = triangle.latest_diagonal

### Development

In [11]:
cl_estimator = cl.Chainladder()

cl_model = cl_estimator.fit(triangle)

ultimates = cl_model.ultimate_

full_projection = cl_model.full_triangle_

In [53]:
reserves = ultimates - triangle.latest_diagonal
reserves.to_frame()

                    2261
2001-01-01           NaN
2002-01-01  9.463381e+04
2003-01-01  4.695113e+05
2004-01-01  7.096378e+05
2005-01-01  9.848886e+05
2006-01-01  1.419459e+06
2007-01-01  2.177641e+06
2008-01-01  3.920301e+06
2009-01-01  4.278972e+06
2010-01-01  4.625811e+06

In [52]:
pd.concat([latest.to_frame(), ultimates.to_frame(), reserves.to_frame()], axis=1, keys=["Latest", "Ultimate", "Reserve"])

               Latest      Ultimate       Reserve
                 2010          2261          2261
2001-01-01  3901463.0  3.901463e+06           NaN
2002-01-01  5339085.0  5.433719e+06  9.463381e+04
2003-01-01  4909315.0  5.378826e+06  4.695113e+05
2004-01-01  4588268.0  5.297906e+06  7.096378e+05
2005-01-01  3873311.0  4.858200e+06  9.848886e+05
2006-01-01  3691712.0  5.111171e+06  1.419459e+06
2007-01-01  3483130.0  5.660771e+06  2.177641e+06
2008-01-01  2864498.0  6.784799e+06  3.920301e+06
2009-01-01  1363294.0  5.642266e+06  4.278972e+06
2010-01-01   344014.0  4.969825e+06  4.625811e+06

In [13]:
full_projection

          12            24            36            48            60            72            84            96            108           120           132           9999
2001  357848.0  1.124788e+06  1.735330e+06  2.218270e+06  2.745596e+06  3.319994e+06  3.466336e+06  3.606286e+06  3.833515e+06  3.901463e+06  3.901463e+06  3.901463e+06
2002  352118.0  1.236139e+06  2.170033e+06  3.353322e+06  3.799067e+06  4.120063e+06  4.647867e+06  4.914039e+06  5.339085e+06  5.433719e+06  5.433719e+06  5.433719e+06
2003  290507.0  1.292306e+06  2.218525e+06  3.235179e+06  3.985995e+06  4.132918e+06  4.628910e+06  4.909315e+06  5.285148e+06  5.378826e+06  5.378826e+06  5.378826e+06
2004  310608.0  1.418858e+06  2.195047e+06  3.757447e+06  4.029929e+06  4.381982e+06  4.588268e+06  4.835458e+06  5.205637e+06  5.297906e+06  5.297906e+06  5.297906e+06
2005  443160.0  1.136350e+06  2.128333e+06  2.897821e+06  3.402672e+06  3.873311e+06  4.207459e+06  4.434133e+06  4.773589e+06  4.858200e+06  4.858200e+06  4.858200e+06
2006  396132.0  1.333217e+06  2.180715e+06  2.985752e+06  3.691712e+06  4.074999e+06  4.426546e+06  4.665023e+06  5.022155e+06  5.111171e+06  5.111171e+06  5.111171e+06
2007  440832.0  1.288463e+06  2.419861e+06  3.483130e+06  4.088678e+06  4.513179e+06  4.902528e+06  5.166649e+06  5.562182e+06  5.660771e+06  5.660771e+06  5.660771e+06
2008  359480.0  1.421128e+06  2.864498e+06  4.174756e+06  4.900545e+06  5.409337e+06  5.875997e+06  6.192562e+06  6.666635e+06  6.784799e+06  6.784799e+06  6.784799e+06
2009  376686.0  1.363294e+06  2.382128e+06  3.471744e+06  4.075313e+06  4.498426e+06  4.886502e+06  5.149760e+06  5.544000e+06  5.642266e+06  5.642266e+06  5.642266e+06
2010  344014.0  1.200818e+06  2.098228e+06  3.057984e+06  3.589620e+06  3.962307e+06  4.304132e+06  4.536015e+06  4.883270e+06  4.969825e+06  4.969825e+06  4.969825e+06